### PR TITLE
Deathsquads no longer have 100% damge resistances

### PR DESCRIPTION
**Pull request by ZephyrTFA**
Deathsquads are intended to be the holy grail of ERTs, not literally gods.

### CODE REVIEW

**Comment by Oscari-pog** [comment]
They are admin-spawn only for a reason

**Comment by ghost** [comment]
>admin-only spawn
>0 base chance to spawn

The actual state of coders.
1 my pain

**Comment by ilikesaying** [comment]
>nerfing ERT that can only spawn via admin fuckery due to a base spawn chance of _**0**_

**Comment by SpaceLoveSs13** [comment]
This is not needed

**Comment by ZephyrTFA** [comment]
This was just me malding.

**Pull request closed without merging**
